// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgIc6LJK7LsZhRN48lG06bWJ_NajqCM8o',
    appId: '1:617757405334:web:ee9db152b6e4d4652d92b7',
    messagingSenderId: '617757405334',
    projectId: 'thsyd-c22f7',
    authDomain: 'thsyd-c22f7.firebaseapp.com',
    storageBucket: 'thsyd-c22f7.appspot.com',
    measurementId: 'G-K2TMXGKDM7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDldKl9OKW19oLo5n0MGeVc_GC3aHBX5yU',
    appId: '1:617757405334:android:f6ff9dfa736c45652d92b7',
    messagingSenderId: '617757405334',
    projectId: 'thsyd-c22f7',
    storageBucket: 'thsyd-c22f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALa3wUek4ese2XVythhOXpF3pRbN-TOwE',
    appId: '1:617757405334:ios:e4d9474322b397ea2d92b7',
    messagingSenderId: '617757405334',
    projectId: 'thsyd-c22f7',
    storageBucket: 'thsyd-c22f7.appspot.com',
    iosBundleId: 'com.example.thsyd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALa3wUek4ese2XVythhOXpF3pRbN-TOwE',
    appId: '1:617757405334:ios:0152f023dc00cedc2d92b7',
    messagingSenderId: '617757405334',
    projectId: 'thsyd-c22f7',
    storageBucket: 'thsyd-c22f7.appspot.com',
    iosBundleId: 'com.example.thsyd.RunnerTests',
  );
}
